-- MySQL Script generated by MySQL Workbench
-- 01/09/16 14:22:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema heihei
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heihei
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heihei` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `heihei` ;

-- -----------------------------------------------------
-- Table `heihei`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heihei`.`userinfo` (
  `uid` INT UNSIGNED NOT NULL,
  `truename` VARCHAR(45) NOT NULL,
  `birthday` VARCHAR(45) NULL,
  `sex` INT NOT NULL DEFAULT 1 COMMENT '默认1男',
  `qq` INT NULL,
  `weixin` VARCHAR(45) NULL,
  `phone` INT NULL,
  `provinceid` INT NULL,
  `citiesid` INT NULL,
  `areasid` INT NULL,
  `address` VARCHAR(45) NULL,
  `hobby` VARCHAR(225) NULL,
  `university` VARCHAR(45) NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `heihei`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heihei`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT UNSIGNED NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `registertime` DATETIME NOT NULL,
  `registerip` VARCHAR(15) NOT NULL,
  `power` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `userinfo_uid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `uid`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_userinfo_idx` (`userinfo_uid` ASC),
  CONSTRAINT `fk_user_userinfo`
    FOREIGN KEY (`userinfo_uid`)
    REFERENCES `heihei`.`userinfo` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `heihei`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heihei`.`state` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT UNSIGNED NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `time` DATETIME NOT NULL,
  `solved` INT NOT NULL DEFAULT 0 COMMENT '0代表默认未被领取解决，1代表正在被解决，2代表已确认解决',
  PRIMARY KEY (`id`, `uid`),
  INDEX `uid` (`uid` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_statement_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `heihei`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `heihei`.`statement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heihei`.`statement` (
  `id` INT NOT NULL,
  `scomment` VARCHAR(255) NULL,
  `scid` INT NOT NULL,
  `sctime` DATETIME NOT NULL,
  `sid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_statement_state1_idx` (`sid` ASC),
  CONSTRAINT `fk_statement_state1`
    FOREIGN KEY (`sid`)
    REFERENCES `heihei`.`state` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `heihei`.`help`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heihei`.`help` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `helperuid` INT NOT NULL,
  `helptime` DATETIME NOT NULL,
  `sid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`sid` ASC),
  CONSTRAINT `fk_helper_state1`
    FOREIGN KEY (`sid`)
    REFERENCES `heihei`.`state` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `heihei`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heihei`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fpower` INT NOT NULL DEFAULT 0 COMMENT '默认0，代表不屏蔽\n1代表屏蔽ta',
  `uid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`uid` ASC),
  CONSTRAINT `fk_friends_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `heihei`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
